FROM node:22.1.0-alpine3.18

WORKDIR /app

RUN npm i -g @nestjs/cli

# COPY ./package*.json .

# RUN npm install

# CMD [ "npm", "run", "start:dev" ]
# CMD [ "/bin/sh", "-c", "npm install && npm run start:dev" ]

VOLUME [ "/app/node_modules" ]