FROM node:22.1.0-alpine3.18

WORKDIR /app

RUN npm i -g @nestjs/cli

COPY ./package*.json .

RUN npm install

# Test something like this
# CMD [ "sh", "-c", "npm install && npm run start:dev" ]
CMD [ "npm", "run", "start:dev" ]

EXPOSE 27017 7101